apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "future.fullname" . }}-scheduler
  labels:
    app: {{ template "future.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "future.chart" . }}
    component: scheduler
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: {{ template "future.name" . }}
      release: {{ .Release.Name | quote }}
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "future.name" . }}
        release: {{ .Release.Name | quote }}
        component: scheduler
    spec:
      imagePullSecrets:
        {{- toYaml .Values.scheduler.image.pullSecrets | nindent 8 }}
      containers:
        - name: {{ template "future.fullname" . }}-scheduler
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          args:
            - sh
            - -c
            - "echo R_PARALLEL_PORT={{ .Values.scheduler.RfuturePort }} NUM_FUTURE_WORKERS={{ .Values.worker.replicas }} >> /usr/local/lib/R/etc/Renviron && Rscript -e 'setup_kube()' && PASSWORD={{ .Values.scheduler.RStudioPassword }} /init"
          ports:
            - containerPort: {{ .Values.scheduler.RfuturePort }}
            - containerPort: {{ .Values.scheduler.servicePort }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          env:
            {{- toYaml .Values.scheduler.env | nindent 12 }}
    {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
